version: "3"

services:
# mysql container
  mysql_database:
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: wp_db
        MYSQL_USER: wp_user
        MYSQL_PASSWORD: 1234
      volumes:
        - mysql:/var/lib/mysql
  
# wordpress container
  wordpress:
    depends_on:
      - mysql_database
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql_database:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: wp_db
    volumes:
      ["./:/var/www/html"]






  
